@startuml app-onboard-and-artefact-management-simplified
!pragma teoz true

'skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    'ParticipantFontSize 20
    'ParticipantFontStyle bold
    'MessageFontSize 12
    MessageFontStyle bold
    ArrowThickness 2
    LifeLineBorderThickness 2
}

actor "User/Consumer" as user

participant "Artefact Manager" as am #FAD9D5

participant "Artefact Registry #1" as ar1 #d5faf2ff
participant "Artefact Registry #2" as ar2 #f7b55fff

note right am #white: Artefact\nManagement API

user -> am: Copy Artefact\n(artifact name, source, destination) (1)
am -> ar1: Download Artefact\n(source) (2.a)
ar1 --> am: Artefact Data (2.b)

am -> ar2: Upload Artefact\n(destination) (3.a)
ar2 --> am: Upload Confirmation (3.b)

am --> user: Copy Artefact Response\n(Success/Failure) (4)
@enduml
