@startuml app-deployment
!pragma teoz true

'skinparam ParticipantPadding 20
skinparam BoxPadding 10

skinparam sequence {
    'ParticipantFontSize 20
    'ParticipantFontStyle bold
    'MessageFontSize 12
    MessageFontStyle bold
    ArrowThickness 2
    LifeLineBorderThickness 2
}

participant "Application\nProvider" as app

box "\nOriginating SOP\n" #DAE8FC
participant "Open Exposure\nGateway" as oeg1 #FAD9D5
participant "Federation\nManager" as fm1 #FAD9D5
end box

box "\nPartner SOP\n" #FFE6CC
participant "Federation\nManager" as fm2 #FAD9D5
box "Open SDK" #FAD7AC
participant "Edge Cloud \nTF" as tf2 #FAD9D5
end box
end box

participant "Edge Cloud\nPlatform" as ecp2 #FFCC99

note right app #white: CAMARA Edge App.\nManagement API
app -> oeg1: App. Instantiation Req.\n(Partner SOP Zone)
note right oeg1 #white: GSMA App. Deployment\nManagement API
oeg1 -> fm1: App. Instantiation Req.\n(Partner SOP Zone)
fm1 -> fm2: App. Instantiation Req.\n(Partner SOP Zone)

fm2 -> fm2: Register App.\nInstantiation Req.

fm2 -> tf2: App. Instantiation Req.
tf2 -> ecp2: App. Instantiation Req.
ecp2 <-> ecp2: Instantiate App.

ecp2 --> tf2: ACK
tf2 --> fm2:ACK

fm2 --> fm1: ACK
fm1 --> oeg1: ACK
oeg1 --> app: App. Instance Status Response\n(App Inst. Identifier)

@enduml
